version: '3'

services:

  #  secrets:
  #   - my_secrets
  #  secrets:
  #   my_secrets:
  #    file: ./secrets.txt

  database:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: typescript-koa
      POSTGRES_PASSWORD: typescript-koa
      POSTGRES_USER: Inez

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery